config/routes.rb
Rails.application.routes.draw do
  get 'answers/create'
  root "questions#index"
  resources :users, only: %i[new create show edit update]
  resources :questions do
    get 'mine', on: :member
    resources :answers, only: %i[create]
  end
  resources :industries, only: %i[index]
  resources :likes, only: %i[create destroy]

  get 'tops/index', to: 'tops#index'
  get 'login', to: 'user_sessions#new'
  get 'recommendation', to: 'user_sessions#modal'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_professions, dependent: :destroy
  has_many :professions, through: :question_professions
  accepts_nested_attributes_for :question_professions
  has_many :answers, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  validates :subject, length: { maximum: 255 }, presence: true
  validates :keyword, length: { maximum: 255 }, presence: true
  validates :body, length: { maximum: 65_535 }, presence: true
  validate :finish_check

  scope :other, ->(question) { where.not(id: question.id) }

  def finish_check
    return if deadline.blank?

    if Time.current.hour < 12
      errors.add(:deadline, 'は明日以降の時間を選択してください') if deadline < Time.current.midnight.tomorrow
    elsif deadline < Time.current.midnight.since(2.days)
      errors.add(:deadline, 'は明後日以降の時間を選択してください')
    end
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[body subject]
  end

  def self.ransackable_associations(_auth_object = nil)
    ['professions']
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :set_question, only: %i[show edit update destroy]
  before_action :set_industries, only: %i[new create]

  # GET /questions or /questions.json
  def index
    # application_controllerに記載
  end

  # GET /questions/1 or /questions/1.json
  def show
    @question = Question.includes(:professions, answers: :user).find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(id: :desc).page(params[:page])
    similar = Question.other(@question).ransack(subject_or_body_cont_any: key_word(@question))
    @similar_questions = similar.result(distinct: true).includes(:professions).page(params[:page]).per(10)
  end

  # GET /questions/new
  def new
    @form = QuestionForm.new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @form = QuestionForm.new(question_params)

    if @form.save
      redirect_to root_path, flash: { success: '質問を作成しました' }
    else
      flash.now[:error] = '不備があります'
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @uestion = current_user.questions.find(params[:id])
    @uestion.destroy!
    redirect_to root_path, status: :see_other, success: '質問を削除しました'
  end

  def mine
    @questions = Question.where(user_id: current_user.id).includes(:professions).page(params[:page]).per(10)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_industries
    @industries = Profession.industries
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question_form)
          .permit(:subject, :body, :deadline_time, :deadline_date, profession_ids: [])
          .merge(user_id: current_user.id)
  end

  def key_word(word)
    word.keyword.split(',')
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_profession.html.erb
<div>
  <div class='badge border-green-600 text-sm'><%=profession.industry%></div>
</div>

app/views/questions/_question.html.erb
<%= link_to  question_path(question), class: "border border-green-600 h-32 rounded opacity-80 w-full shadow-lg" do %>
  <div class='relative h-full flex flex-col'>
    <div class='m-0.5 flex flex-wrap'>
      <%=render partial: 'questions/profession', collection:question.professions, as: 'profession'%>
    </div>
    <div class='absolute flex items-center ml-2 h-full'><%= question.subject %></div>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="hero bg-white py-12">
  <div class="flex flex-col w-7/12 space-y-4">
    <p class='text-center text-3xl'>質問一覧</p>
    <%= render(@questions) || content_tag(:p, '質問がありません',class: "text-center text-xl") %>
    <div class='flex justify-center'>
      <%= paginate @questions %>
    </div>
  </div>
</div>

app/views/questions/mine.html.erb
<div class="hero bg-white py-12">
  <div class="flex flex-col w-7/12 space-y-4">
    <p class='text-center text-3xl'>質問履歴</p>
    <%= render(@questions) || content_tag(:p, '質問履歴はありません', class: "text-center text-xl") %>
    <div class='flex justify-center'>
      <%= paginate @questions %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="hero bg-white py-12">
    <div class="shrink-0 shadow-xl bg-base-100 bg-white rounded-2xl w-2/5 min-w-96">
    <%= form_with model: @form, url: questions_path, class:"card-body" do |f| %>
      <div class="flex justify-center text-2xl">質問作成</div>
      <div class="form-control">
        <%= render 'hidden/error_message', model: @form %>
      </div>
      <div class="form-control">
        <div class="pb-2 label-text">
        <%= t("activerecord.attributes.question.subject") %><span class="text-red-500">※</span>
        </div>
        <%= f.text_area :subject, class:'textarea textarea-success w-full', placeholder:"5文字以上入力してください" %>
      </div>
      <div class="form-control">
        <div class="pb-2 label-text">
        <%= t("activerecord.attributes.question.body") %><span class="text-red-500">※</span>
        </div>
        <%= f.text_area :body, class: 'textarea textarea-success h-60 w-full', placeholder:"5文字以上入力してください" %>
      </div>
      <div class="form-control">
        <div class="label label-text">締切期間</div>
        <div class="flex w-full space-x-1">
          <%= f.date_field :deadline_date, min:Date.tomorrow, class:'w-full border border-green-600 rounded'%>
          <%= f.select :deadline_time, (0..23).map(&:to_s), { include_blank: "時間" }, class:'w-full border border-green-600 rounded'%>
        </div>
      </div>
      <div class="label-text">業種(複数選択可)<span class="text-red-500">※</span></div>
      <div class='grid grid-rows-3 grid-flow-row grid-flow-col'>
        <%= f.collection_check_boxes :profession_ids, @industries, :last, :first, include_hidden: false do |q| %>
          <div class='flex items-center'>
            <%= q.check_box(class: 'checkbox checkbox-success checkbox-xs') %>
            <%= q.label {q.text} %>
          </div>
        <% end %>
      </div>
      <div>
        <span class="text-red-500">※</span>は必須項目です
      </div>
      <div class="form-control mt-4">
        <%= f.submit "質問を作成する", class: "btn bg-green-500 hover:bg-green-600 w-full" %>
      </div>
    <% end %>
    <div class="form-control">
    </div>
    </div>
</div>

app/views/questions/show.html.erb
<div class="hero bg-white" data-controller='check-out' data-check-out-target='backGround'data-action='click->check-out#change'>
  <div class="w-3/6 py-8 space-y-4" data-action='click->check-out#change'>
    <div class="px-4 py-2 border-2 border-green-600 space-y-1">
    <p class='text-right'>
      <%= @question.decorate.deadline_days if @question.deadline.present? %>
    </p>
    <div class='flex justify-end flex-wrap'>
      <%=render partial: 'profession', collection:@question.professions, as: 'profession'%>
    </div>
    <div class="flex items-center">
        <%= link_to  user_path(@question.user), class: "flex items-center justify-between" do %>
          <i class="fa-solid fa-circle-user fa-2x pr-2"></i>
          <div class="text-xl"><%= @question.user.name %></div>
        <% end %>
      </div>
      <div class="text-3xl"><%= @question.subject %></div>
      <div class="flex items-center"><%= @question.body %></div>
      <div class="flex justify-end space-x-1">
        <% if @question.likes.exists?(user_id: current_user)  %>
          <%= render partial: 'likes/like', locals: { type: @question.likes } %>
        <% else %>
          <%= render partial: 'likes/notlike', locals: { type: @question } %>
        <% end %>
        <% if @question.user == current_user && @answers.empty? %>
          <%= link_to '削除', question_path(@question), class: 'text-green-600 border border-green-600 p-1 rounded hover:text-gray-300 hover:border-gray-300', data: { turbo_method: :delete } %>
        <% end %>
      </div>
    </div>
    <% if logged_in? %>
    <div>
      <div class="collapse bg-base-200 border-2 border-green-600 rounded-none bg-white">
        <input type="checkbox" id='rspec_check' data-check-out-target='checkBox'> 
        <div class="text-center collapse-title text-xl bg-white" >
          <div data-check-out-target='text'>回答する</div>
        </div>
        <%= render partial: 'answers/form', locals: { answer: @answer, question: @question } %>
      </div>
    </div>
    <% else %>
      <%= link_to '回答する', recommendation_path, class:'btn bg-green-500 hover:bg-green-600 w-full text-white', data: { turbo_frame: 'review_modal' } %>
    <% end %>
    <div class ='space-y-3' id='table-answer'>
      <% if @answers.present? %>
        <p class='text-center text-xl'>回答一覧</p>
        <%= render partial: 'answers/answer', collection: @answers %>
        <div class='flex justify-center'>
          <%= paginate @answers %>
        </div>
      <% else %>
        <p class='text-center text-xl'>回答なし</p>
      <% end %>
    </div>
    <div class ='flex flex-col space-y-2' id=rspec_answer>
      <% if @similar_questions.present? %>
        <p class='text-center text-xl'>類似した質問一覧</p>
        <%=render partial: 'question', collection:@similar_questions, as: 'question'%>
        <div class='flex justify-center'>
          <%= paginate @similar_questions %>
        </div>
     <% else %>
        <p class='text-center text-xl'>類似した質問はありません</p>
     <% end %>
    </div>
  </div>
</div>