config/routes.rb
Rails.application.routes.draw do
  get 'answers/create'
  root "questions#index"
  resources :users, only: %i[new create show edit update]
  resources :questions do
    get 'mine', on: :member
    resources :answers, only: %i[create]
  end
  resources :industries, only: %i[index]
  resources :likes, only: %i[create destroy]

  get 'tops/index', to: 'tops#index'
  get 'login', to: 'user_sessions#new'
  get 'recommendation', to: 'user_sessions#modal'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  with_options presence: true do
    validates :likeable_type
    validates :likeable_id, uniqueness: { scope: [:likeable_type, :user_id],
                                          message: 'はすでに同じデータが存在します' }
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[destroy]

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)
    @like.save
    @likes = Like.where(likeable_id: @like.likeable_id, likeable_type: @like.likeable_type)
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like.destroy!
  end

  private

  def set_like
    @like = Like.find(params[:id])
  end

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type).merge(user_id: current_user.id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%= link_to like_path(id:type.find_by(user_id: current_user.id)), data: { turbo_method: :delete },
            class: 'text-green-600 border border-green-600 p-1 rounded hover:text-gray-300 hover:border-gray-300', id:"like-#{type[0].likeable_type}-#{type[0].likeable_id}" do %>
  <i class="fa-solid fa-thumbs-up"></i>
  <%= type.count %>
<% end %>

app/views/likes/_notlike.html.erb
<%= link_to likes_path(like:{likeable_id:type,likeable_type:type.class.name}), data: { "turbo-method": :post }, 
              class: 'text-gray-400 border border-gray-400 p-1 rounded hover:text-gray-300 hover:border-gray-300', id:"notlike-#{type.class.name}-#{type.id}" do %>
  <i class="fa-regular fa-thumbs-up"></i>
  <%= type.likes.count %>
<% end %>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace "notlike-#{@like.likeable_type}-#{@like.likeable_id}" do %>
  <%= render partial: 'likes/like', locals: { type: @likes } %>
<% end %>

app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.replace "like-#{@like.likeable_type}-#{@like.likeable_id}" do %>
  <%= render partial: 'likes/notlike', locals: { type: @like.likeable } %>
<% end  %>