config/routes.rb
Rails.application.routes.draw do
  get 'answers/create'
  root "questions#index"
  resources :users, only: %i[new create show edit update]
  resources :questions do
    get 'mine', on: :member
    resources :answers, only: %i[create]
  end
  resources :industries, only: %i[index]
  resources :likes, only: %i[create destroy]

  get 'tops/index', to: 'tops#index'
  get 'login', to: 'user_sessions#new'
  get 'recommendation', to: 'user_sessions#modal'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer class="border-t-2 border-green-600 py-8">
 <div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 flex items-center justify-center">
      <ul class="flex flex-col space-x-1 items-center">
        <li><a href="#" class="text-green-600 hover:text-gray-300">このサイトの使い方</a></li>
        <li><a href="#" class="text-green-600 hover:text-gray-300 text-center">利用規約</a></li>
        <li><a href="#" class="text-green-600 hover:text-gray-300 text-center">プライバシーポリシー</a></li>
      </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky top-0 z-10">
  <nav class="border-4 border-green-600 p-8 bg-white">
    <div class="container mx-auto flex justify-between items-center">
      <%= render 'layouts/search' %>
      <div class="flex space-x-4">
        <%= logged_in? ? render('layouts/login') : render('layouts/logout') %>
        <%= link_to logged_in? ? new_question_path : recommendation_path, class: "text-green-600 hover:text-gray-300",data: ({ turbo_frame: 'review_modal' } unless logged_in?) do %>
          <div class="flex flex-col">
            <i class="fa fa-question fa-lg"></i>
            <p>質問する</p>
          </div>
        <% end %>
        <%= link_to  industries_path, class: "text-green-600 hover:text-gray-300" do %>
          <div class="flex flex-col">
            <i class="fa-solid fa-list fa-lg"></i>
            <p>カテゴリ</p>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_login.html.erb
<div class="dropdown dropdown-end dropdown-hover">
  <label tabindex="0" class="flex flex-col text-green-600 hover:text-gray-300">
    <i class="fa-solid fa-circle-user fa-lg"></i>
    <p><%= current_user.name %></p>
  </label>
  <div tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
    <li><%= link_to "プロフィール", user_path(current_user),class: "text-green-600 hover:text-gray-300"%></li>
    <li><%= link_to "質問履歴", mine_question_path(current_user),class: "text-green-600 hover:text-gray-300"%></li>
    <li><%= link_to "ログアウト", logout_path, class: "text-green-600 hover:text-gray-300", data: { turbo_method: :delete } %></li>
  </div>
</div>  

app/views/layouts/_logout.html.erb
<%= link_to login_path ,class: "text-green-600 hover:text-gray-300" do %>
  <div class="flex flex-col">
    <i class="fa-solid fa-right-to-bracket fa-lg"></i>
    <p>ログイン</p>
  </div>
<% end %>
<%= link_to  new_user_path, class: "text-green-600 hover:text-gray-300" do %>
  <div class="flex flex-col">
    <i class="fa-regular fa-address-card fa-lg"></i>
    <p>新規登録</p>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<div class="flex items-center space-x-4">
  <%= link_to "教えて先輩!", root_path, class: "text-green-600 hover:text-gray-300 text-3xl font-fine" %>
  <% unless ['new', 'edit','modal'].include?(action_name) %>
    <%= search_form_for @search, url: questions_path do |f| %>
      <div class='join h-8'>
        <%= f.text_field :subject_or_body_cont, placeholder: "気になるワードを入力", class:'border join-item' %>
        <%= f.submit "検索", class:'bg-green-500 hover:bg-green-400 join-item text-white' %>
      </div>
    <% end %>  
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application",'data-turbolinks-track': "reload", defer: true %>
  </head>

  <body>
    <div id='modal'></div>
    <%= turbo_frame_tag 'review_modal' %>
    <%= render 'layouts/header' %>
    <%= render 'hidden/flash_message' %>
     <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>